### ISSUE TITLE
Requesting new Feture

### ISSUE THREAD

**Issue by wonderlandpark** [cotwo0139/slyrics#4]
Your library is super nice.

It would be great if you make youtube music Voice recognition lyrics function.

**Comment by sangoonisgoja** [comment]
我同意你的看法
这是这些功能之一

**Comment by cotwo0139** [comment]
가능하시다면 직접 기능을 구현하시고 PR을 남겨주세요.

**Comment by sangoonisgoja** [comment]
나에게는 구현하기 어렵지만 산군님은 구현하실 수 있을거십니다.
기대해보겠습니다.
귀엽고 깜찍한 산군산군 산구리라따 님

**Comment by sangoonisgoja** [comment]
@cotwo0139

**Comment by sangoonisgoja** [comment]
我很难实施，但是您可以做到。
我很期待。
可爱又可爱的三郡山郡Sangurirata
